// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P03_SalesDatabase.Data;

#nullable disable

namespace P03_SalesDatabase.Data.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20240701082601_AddedSeeding")]
    partial class AddedSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreditCardNumber = "0000 0000 0000 9691",
                            Email = "customer1@example.com",
                            Name = "Customer1"
                        },
                        new
                        {
                            CustomerId = 2,
                            CreditCardNumber = "0000 0000 0000 5981",
                            Email = "customer2@example.com",
                            Name = "Customer2"
                        },
                        new
                        {
                            CustomerId = 3,
                            CreditCardNumber = "0000 0000 0000 8315",
                            Email = "customer3@example.com",
                            Name = "Customer3"
                        },
                        new
                        {
                            CustomerId = 4,
                            CreditCardNumber = "0000 0000 0000 4381",
                            Email = "customer4@example.com",
                            Name = "Customer4"
                        },
                        new
                        {
                            CustomerId = 5,
                            CreditCardNumber = "0000 0000 0000 8874",
                            Email = "customer5@example.com",
                            Name = "Customer5"
                        },
                        new
                        {
                            CustomerId = 6,
                            CreditCardNumber = "0000 0000 0000 1678",
                            Email = "customer6@example.com",
                            Name = "Customer6"
                        },
                        new
                        {
                            CustomerId = 7,
                            CreditCardNumber = "0000 0000 0000 6206",
                            Email = "customer7@example.com",
                            Name = "Customer7"
                        },
                        new
                        {
                            CustomerId = 8,
                            CreditCardNumber = "0000 0000 0000 9076",
                            Email = "customer8@example.com",
                            Name = "Customer8"
                        },
                        new
                        {
                            CustomerId = 9,
                            CreditCardNumber = "0000 0000 0000 4146",
                            Email = "customer9@example.com",
                            Name = "Customer9"
                        },
                        new
                        {
                            CustomerId = 10,
                            CreditCardNumber = "0000 0000 0000 1555",
                            Email = "customer10@example.com",
                            Name = "Customer10"
                        },
                        new
                        {
                            CustomerId = 11,
                            CreditCardNumber = "0000 0000 0000 4558",
                            Email = "customer11@example.com",
                            Name = "Customer11"
                        },
                        new
                        {
                            CustomerId = 12,
                            CreditCardNumber = "0000 0000 0000 8383",
                            Email = "customer12@example.com",
                            Name = "Customer12"
                        },
                        new
                        {
                            CustomerId = 13,
                            CreditCardNumber = "0000 0000 0000 3407",
                            Email = "customer13@example.com",
                            Name = "Customer13"
                        },
                        new
                        {
                            CustomerId = 14,
                            CreditCardNumber = "0000 0000 0000 4025",
                            Email = "customer14@example.com",
                            Name = "Customer14"
                        },
                        new
                        {
                            CustomerId = 15,
                            CreditCardNumber = "0000 0000 0000 7454",
                            Email = "customer15@example.com",
                            Name = "Customer15"
                        },
                        new
                        {
                            CustomerId = 16,
                            CreditCardNumber = "0000 0000 0000 3897",
                            Email = "customer16@example.com",
                            Name = "Customer16"
                        },
                        new
                        {
                            CustomerId = 17,
                            CreditCardNumber = "0000 0000 0000 3133",
                            Email = "customer17@example.com",
                            Name = "Customer17"
                        },
                        new
                        {
                            CustomerId = 18,
                            CreditCardNumber = "0000 0000 0000 6089",
                            Email = "customer18@example.com",
                            Name = "Customer18"
                        },
                        new
                        {
                            CustomerId = 19,
                            CreditCardNumber = "0000 0000 0000 9652",
                            Email = "customer19@example.com",
                            Name = "Customer19"
                        },
                        new
                        {
                            CustomerId = 20,
                            CreditCardNumber = "0000 0000 0000 9894",
                            Email = "customer20@example.com",
                            Name = "Customer20"
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Product1",
                            Price = 715.886626816514m,
                            Quantity = 85m
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Product2",
                            Price = 472.758330157478m,
                            Quantity = 18m
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Product3",
                            Price = 44.7385604921745m,
                            Quantity = 90m
                        },
                        new
                        {
                            ProductId = 4,
                            Name = "Product4",
                            Price = 812.061024763184m,
                            Quantity = 31m
                        },
                        new
                        {
                            ProductId = 5,
                            Name = "Product5",
                            Price = 346.860975203073m,
                            Quantity = 19m
                        },
                        new
                        {
                            ProductId = 6,
                            Name = "Product6",
                            Price = 92.4866277855415m,
                            Quantity = 73m
                        },
                        new
                        {
                            ProductId = 7,
                            Name = "Product7",
                            Price = 31.8685121399691m,
                            Quantity = 68m
                        },
                        new
                        {
                            ProductId = 8,
                            Name = "Product8",
                            Price = 2.20596237637582m,
                            Quantity = 41m
                        },
                        new
                        {
                            ProductId = 9,
                            Name = "Product9",
                            Price = 965.189283461139m,
                            Quantity = 65m
                        },
                        new
                        {
                            ProductId = 10,
                            Name = "Product10",
                            Price = 303.589661231976m,
                            Quantity = 66m
                        },
                        new
                        {
                            ProductId = 11,
                            Name = "Product11",
                            Price = 142.048446020546m,
                            Quantity = 70m
                        },
                        new
                        {
                            ProductId = 12,
                            Name = "Product12",
                            Price = 677.275943870152m,
                            Quantity = 61m
                        },
                        new
                        {
                            ProductId = 13,
                            Name = "Product13",
                            Price = 173.98110166669m,
                            Quantity = 68m
                        },
                        new
                        {
                            ProductId = 14,
                            Name = "Product14",
                            Price = 752.640530170056m,
                            Quantity = 68m
                        },
                        new
                        {
                            ProductId = 15,
                            Name = "Product15",
                            Price = 921.877557540711m,
                            Quantity = 13m
                        },
                        new
                        {
                            ProductId = 16,
                            Name = "Product16",
                            Price = 535.012174780144m,
                            Quantity = 72m
                        },
                        new
                        {
                            ProductId = 17,
                            Name = "Product17",
                            Price = 960.467787302992m,
                            Quantity = 52m
                        },
                        new
                        {
                            ProductId = 18,
                            Name = "Product18",
                            Price = 332.581520725301m,
                            Quantity = 23m
                        },
                        new
                        {
                            ProductId = 19,
                            Name = "Product19",
                            Price = 446.413119465568m,
                            Quantity = 19m
                        },
                        new
                        {
                            ProductId = 20,
                            Name = "Product20",
                            Price = 721.53510012853m,
                            Quantity = 12m
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            CustomerId = 17,
                            Date = new DateTime(2024, 2, 26, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(1952),
                            ProductId = 2,
                            StoreId = 8
                        },
                        new
                        {
                            SaleId = 2,
                            CustomerId = 10,
                            Date = new DateTime(2022, 10, 3, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(1990),
                            ProductId = 9,
                            StoreId = 1
                        },
                        new
                        {
                            SaleId = 3,
                            CustomerId = 8,
                            Date = new DateTime(2023, 10, 2, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(1994),
                            ProductId = 18,
                            StoreId = 4
                        },
                        new
                        {
                            SaleId = 4,
                            CustomerId = 5,
                            Date = new DateTime(2022, 9, 4, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(1998),
                            ProductId = 2,
                            StoreId = 1
                        },
                        new
                        {
                            SaleId = 5,
                            CustomerId = 6,
                            Date = new DateTime(2024, 1, 27, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2000),
                            ProductId = 9,
                            StoreId = 4
                        },
                        new
                        {
                            SaleId = 6,
                            CustomerId = 6,
                            Date = new DateTime(2023, 3, 27, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2005),
                            ProductId = 7,
                            StoreId = 5
                        },
                        new
                        {
                            SaleId = 7,
                            CustomerId = 12,
                            Date = new DateTime(2024, 5, 31, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2009),
                            ProductId = 3,
                            StoreId = 3
                        },
                        new
                        {
                            SaleId = 8,
                            CustomerId = 5,
                            Date = new DateTime(2023, 12, 30, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2012),
                            ProductId = 3,
                            StoreId = 1
                        },
                        new
                        {
                            SaleId = 9,
                            CustomerId = 18,
                            Date = new DateTime(2023, 2, 28, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2016),
                            ProductId = 5,
                            StoreId = 1
                        },
                        new
                        {
                            SaleId = 10,
                            CustomerId = 15,
                            Date = new DateTime(2023, 3, 7, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2021),
                            ProductId = 2,
                            StoreId = 3
                        },
                        new
                        {
                            SaleId = 11,
                            CustomerId = 19,
                            Date = new DateTime(2024, 4, 25, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2025),
                            ProductId = 20,
                            StoreId = 4
                        },
                        new
                        {
                            SaleId = 12,
                            CustomerId = 1,
                            Date = new DateTime(2023, 7, 4, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2028),
                            ProductId = 11,
                            StoreId = 8
                        },
                        new
                        {
                            SaleId = 13,
                            CustomerId = 6,
                            Date = new DateTime(2023, 10, 1, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2031),
                            ProductId = 5,
                            StoreId = 10
                        },
                        new
                        {
                            SaleId = 14,
                            CustomerId = 20,
                            Date = new DateTime(2024, 4, 19, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2034),
                            ProductId = 2,
                            StoreId = 8
                        },
                        new
                        {
                            SaleId = 15,
                            CustomerId = 17,
                            Date = new DateTime(2023, 11, 26, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2038),
                            ProductId = 12,
                            StoreId = 4
                        },
                        new
                        {
                            SaleId = 16,
                            CustomerId = 8,
                            Date = new DateTime(2022, 2, 10, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2041),
                            ProductId = 19,
                            StoreId = 2
                        },
                        new
                        {
                            SaleId = 17,
                            CustomerId = 13,
                            Date = new DateTime(2024, 5, 15, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2044),
                            ProductId = 19,
                            StoreId = 3
                        },
                        new
                        {
                            SaleId = 18,
                            CustomerId = 9,
                            Date = new DateTime(2023, 7, 4, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2049),
                            ProductId = 13,
                            StoreId = 8
                        },
                        new
                        {
                            SaleId = 19,
                            CustomerId = 6,
                            Date = new DateTime(2022, 9, 26, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2052),
                            ProductId = 2,
                            StoreId = 2
                        },
                        new
                        {
                            SaleId = 20,
                            CustomerId = 5,
                            Date = new DateTime(2022, 5, 21, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2056),
                            ProductId = 4,
                            StoreId = 3
                        },
                        new
                        {
                            SaleId = 21,
                            CustomerId = 4,
                            Date = new DateTime(2023, 9, 20, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2059),
                            ProductId = 1,
                            StoreId = 10
                        },
                        new
                        {
                            SaleId = 22,
                            CustomerId = 16,
                            Date = new DateTime(2023, 3, 20, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2062),
                            ProductId = 7,
                            StoreId = 6
                        },
                        new
                        {
                            SaleId = 23,
                            CustomerId = 2,
                            Date = new DateTime(2022, 3, 7, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2065),
                            ProductId = 16,
                            StoreId = 6
                        },
                        new
                        {
                            SaleId = 24,
                            CustomerId = 17,
                            Date = new DateTime(2022, 6, 19, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2068),
                            ProductId = 5,
                            StoreId = 3
                        },
                        new
                        {
                            SaleId = 25,
                            CustomerId = 3,
                            Date = new DateTime(2022, 10, 9, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2071),
                            ProductId = 7,
                            StoreId = 7
                        },
                        new
                        {
                            SaleId = 26,
                            CustomerId = 19,
                            Date = new DateTime(2023, 8, 12, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2075),
                            ProductId = 6,
                            StoreId = 8
                        },
                        new
                        {
                            SaleId = 27,
                            CustomerId = 20,
                            Date = new DateTime(2023, 11, 7, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2078),
                            ProductId = 20,
                            StoreId = 1
                        },
                        new
                        {
                            SaleId = 28,
                            CustomerId = 10,
                            Date = new DateTime(2024, 1, 3, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2081),
                            ProductId = 3,
                            StoreId = 4
                        },
                        new
                        {
                            SaleId = 29,
                            CustomerId = 18,
                            Date = new DateTime(2022, 1, 8, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2084),
                            ProductId = 19,
                            StoreId = 10
                        },
                        new
                        {
                            SaleId = 30,
                            CustomerId = 12,
                            Date = new DateTime(2022, 8, 3, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2088),
                            ProductId = 18,
                            StoreId = 4
                        },
                        new
                        {
                            SaleId = 31,
                            CustomerId = 4,
                            Date = new DateTime(2022, 10, 27, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2129),
                            ProductId = 17,
                            StoreId = 4
                        },
                        new
                        {
                            SaleId = 32,
                            CustomerId = 12,
                            Date = new DateTime(2022, 9, 9, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2134),
                            ProductId = 1,
                            StoreId = 9
                        },
                        new
                        {
                            SaleId = 33,
                            CustomerId = 10,
                            Date = new DateTime(2023, 1, 12, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2138),
                            ProductId = 15,
                            StoreId = 2
                        },
                        new
                        {
                            SaleId = 34,
                            CustomerId = 20,
                            Date = new DateTime(2022, 12, 8, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2143),
                            ProductId = 10,
                            StoreId = 2
                        },
                        new
                        {
                            SaleId = 35,
                            CustomerId = 1,
                            Date = new DateTime(2022, 4, 7, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2146),
                            ProductId = 5,
                            StoreId = 3
                        },
                        new
                        {
                            SaleId = 36,
                            CustomerId = 7,
                            Date = new DateTime(2022, 12, 25, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2149),
                            ProductId = 15,
                            StoreId = 9
                        },
                        new
                        {
                            SaleId = 37,
                            CustomerId = 7,
                            Date = new DateTime(2022, 10, 15, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2151),
                            ProductId = 6,
                            StoreId = 1
                        },
                        new
                        {
                            SaleId = 38,
                            CustomerId = 15,
                            Date = new DateTime(2024, 3, 4, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2154),
                            ProductId = 12,
                            StoreId = 7
                        },
                        new
                        {
                            SaleId = 39,
                            CustomerId = 13,
                            Date = new DateTime(2023, 6, 14, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2157),
                            ProductId = 20,
                            StoreId = 6
                        },
                        new
                        {
                            SaleId = 40,
                            CustomerId = 17,
                            Date = new DateTime(2022, 7, 7, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2159),
                            ProductId = 4,
                            StoreId = 10
                        },
                        new
                        {
                            SaleId = 41,
                            CustomerId = 7,
                            Date = new DateTime(2021, 10, 22, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2162),
                            ProductId = 2,
                            StoreId = 7
                        },
                        new
                        {
                            SaleId = 42,
                            CustomerId = 8,
                            Date = new DateTime(2024, 2, 1, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2165),
                            ProductId = 10,
                            StoreId = 9
                        },
                        new
                        {
                            SaleId = 43,
                            CustomerId = 20,
                            Date = new DateTime(2022, 7, 7, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2169),
                            ProductId = 4,
                            StoreId = 7
                        },
                        new
                        {
                            SaleId = 44,
                            CustomerId = 10,
                            Date = new DateTime(2021, 12, 28, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2171),
                            ProductId = 10,
                            StoreId = 8
                        },
                        new
                        {
                            SaleId = 45,
                            CustomerId = 6,
                            Date = new DateTime(2023, 9, 13, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2174),
                            ProductId = 5,
                            StoreId = 2
                        },
                        new
                        {
                            SaleId = 46,
                            CustomerId = 10,
                            Date = new DateTime(2024, 3, 28, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2177),
                            ProductId = 15,
                            StoreId = 7
                        },
                        new
                        {
                            SaleId = 47,
                            CustomerId = 2,
                            Date = new DateTime(2022, 4, 25, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2181),
                            ProductId = 5,
                            StoreId = 2
                        },
                        new
                        {
                            SaleId = 48,
                            CustomerId = 6,
                            Date = new DateTime(2022, 9, 12, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2184),
                            ProductId = 2,
                            StoreId = 9
                        },
                        new
                        {
                            SaleId = 49,
                            CustomerId = 13,
                            Date = new DateTime(2023, 9, 10, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2188),
                            ProductId = 19,
                            StoreId = 6
                        },
                        new
                        {
                            SaleId = 50,
                            CustomerId = 12,
                            Date = new DateTime(2023, 12, 1, 11, 26, 0, 895, DateTimeKind.Local).AddTicks(2191),
                            ProductId = 19,
                            StoreId = 2
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreId = 1,
                            Name = "Store1"
                        },
                        new
                        {
                            StoreId = 2,
                            Name = "Store2"
                        },
                        new
                        {
                            StoreId = 3,
                            Name = "Store3"
                        },
                        new
                        {
                            StoreId = 4,
                            Name = "Store4"
                        },
                        new
                        {
                            StoreId = 5,
                            Name = "Store5"
                        },
                        new
                        {
                            StoreId = 6,
                            Name = "Store6"
                        },
                        new
                        {
                            StoreId = 7,
                            Name = "Store7"
                        },
                        new
                        {
                            StoreId = 8,
                            Name = "Store8"
                        },
                        new
                        {
                            StoreId = 9,
                            Name = "Store9"
                        },
                        new
                        {
                            StoreId = 10,
                            Name = "Store10"
                        });
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Sale", b =>
                {
                    b.HasOne("P03_SalesDatabase.Data.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("P03_SalesDatabase.Data.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("P03_SalesDatabase.Data.Models.Store", "Store")
                        .WithMany("Sales")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("P03_SalesDatabase.Data.Models.Store", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
